[package]
name = "learn-wgpu"
version = "0.0.0"
authors = ["rukai"]
repository = "https://github.com/rust-tutorials/learn-wgpu"
readme = "README.md"
edition = "2018"
description = "A guided introduction to using the wgpu crate"
license = "MIT"

[dependencies]
wgpu = "0.3"
